[package]
name = "akira"
version = "0.1.0"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

[dependencies]
rlibc = "1.0"

[dependencies.efi]
path = "efi"

[lib]
name = "akira"
crate-type = ["staticlib"]
