(function() {var implementors = {};
implementors["efi_sys"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a> for <a class='struct' href='efi_sys/struct.MemoryAttribute.html' title='efi_sys::MemoryAttribute'>MemoryAttribute</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a> for <a class='struct' href='efi_sys/struct.OpenProtocolAttribute.html' title='efi_sys::OpenProtocolAttribute'>OpenProtocolAttribute</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a> for <a class='struct' href='efi_sys/struct.Daylight.html' title='efi_sys::Daylight'>Daylight</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a> for <a class='struct' href='efi_sys/struct.DebugDisposition.html' title='efi_sys::DebugDisposition'>DebugDisposition</a>",];implementors["efi"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='efi/struct.MemoryAttribute.html' title='efi::MemoryAttribute'>MemoryAttribute</a>&gt; for <a class='struct' href='efi/struct.MemoryAttribute.html' title='efi::MemoryAttribute'>MemoryAttribute</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='efi_sys/struct.OpenProtocolAttribute.html' title='efi_sys::OpenProtocolAttribute'>OpenProtocolAttribute</a>&gt; for <a class='struct' href='efi_sys/struct.OpenProtocolAttribute.html' title='efi_sys::OpenProtocolAttribute'>OpenProtocolAttribute</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='efi_sys/struct.Daylight.html' title='efi_sys::Daylight'>Daylight</a>&gt; for <a class='struct' href='efi_sys/struct.Daylight.html' title='efi_sys::Daylight'>Daylight</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='struct' href='efi_sys/struct.DebugDisposition.html' title='efi_sys::DebugDisposition'>DebugDisposition</a>&gt; for <a class='struct' href='efi_sys/struct.DebugDisposition.html' title='efi_sys::DebugDisposition'>DebugDisposition</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
